### ISSUE TITLE
oranda fails with undescriptive error

### ISSUE THREAD

**Issue by spitfire05** [axodotdev/oranda#206] opened 2023-03-08 20:03 UTC
Given a config that only specifies usage of `cargo-dist`:
```json
{
  "artifacts": {
    "cargo_dist": true
  }
}
```

`oranda build` fails with:
```
↪ >o_o< INFO: Running build...
↪ >o_o< INFO: Loading config at ./oranda.json
↪ >o_o< INFO: Detected Rust project...
✗ >o_o< ERROR: error decoding response body: expected value at line 1 column 1
```

When the config is empty / file not existing it builds fine.

The `cargo-dist` is not actually set up in the repo (however, there is a release existing). Doe sit query github releases and that fails? If so, the error should be a bit more descriptive :)

**Comment by SaraVieira** [comment] 2023-03-08 20:57
Hey!

Can you please let me know what is the repo you are using?

**Comment by ashleygwilliams** [comment] 2023-03-08 20:59
hey @spitfire05 - long time no talk :P

i'm running into this too, agree that there's a bunch of error handling work to do around how manage github requests. right now we are assuming success and just immediately trying to parse the body :) i'll put a PR for this later today

**Comment by spitfire05** [comment] 2023-03-09 13:27
@SaraVieira I was playing with oranda using https://github.com/spitfire05/portproxy

@ashleygwilliams hi! 😄 understood, hope better error handling comes soon, as this can be very misleading (I spent quite some time trying to figure out what the hell is wrong with.. the config I provide ;) ).

**Comment by ashleygwilliams** [comment] 2023-03-09 16:00
@spitfire05 #193 has several error handling improvements :) i'm going to merge and cut a release (along with cargo-dist), later today.

we haven't formally released/announced oranda yet largely due to these rough edges (very much appreciate early users giving us feedback!!!) please keep filing things you run into!

**Comment by ashleygwilliams** [comment] 2023-03-09 16:00
specifically: https://github.com/axodotdev/oranda/pull/193/commits/632cc53f98ff565640ddf6375b5741f7b05b1abd#diff-fefa9072271fc2a9538b49a84c25e3ec807581a2cd5a3d7de97703de07436826R50 should fix what you were running into (and we were too!)

**Comment by ashleygwilliams** [comment] 2023-03-10 01:19
this should be fixed as i cannot reproduce it. i'll cut 0.0.2 tomorrow. if that ends up not fixing this, please feel free to reopen @spitfire05 !

**Closed as completed by ashleygwilliams** 2023-03-10 01:19 UTC
Labels: bug - build
